import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Hero } from './hero';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      { id: 12, name: 'Dr. Nice', superpower: 'Nice ray', age: 29 },
      { id: 13, name: 'Bombasto', superpower: 'Exploding sweat', age: 18},
      { id: 14, name: 'Celeritas', superpower: 'True sight', age: 44},
      { id: 15, name: 'Magneta', superpower: 'Magnetic control', age: 37},
      { id: 16, name: 'RubberMan', superpower: 'Elasticity', age: 31},
      { id: 17, name: 'Dynama', superpower: 'Electricity generation', age: 29},
      { id: 18, name: 'Dr. IQ', superpower: '500 IQ', age: 99},
      { id: 19, name: 'Magma', superpower: 'Fire control', age: 51},
      { id: 20, name: 'Tornado', superpower: 'Weather control', age: 22},
      // { id: 21, name: 'Bob', superpower: 'Plumbing', age: 33},
      // { id: 22, name: 'Marjo', superpower: 'Not Plumbing', age: 28},
      // { id: 23, name: 'Rordon Gamsey', superpower: 'Super Chef', age: 58},
      // { id: 24, name: 'Lupusirine', superpower: 'Regeneration and claws', age: 31},
      // { id: 25, name: 'Sand Castle Kid', superpower: 'Sand', age: 10},
      // { id: 26, name: 'Stretchy McStretchy', superpower: 'Stretching', age: 17},
      // { id: 27, name: 'Lace Landwalker', superpower: 'Space wizard', age: 21},
      // { id: 28, name: 'Dr. Annoy', superpower: 'Annoys Everyone', age: 901},
      // { id: 29, name: 'A. Powers', superpower: 'Great parodies', age: 34},
      // { id: 30, name: 'Water Person', superpower: 'Controls water', age: 40},
      // { id: 31, name: 'Air Person', superpower: 'Controls wind', age: 40},
      // { id: 32, name: 'Earth Person', superpower: 'Controls earth', age: 40},
      // { id: 33, name: 'Ether Person', superpower: 'Controls ether', age: 40},
      // { id: 34, name: 'Plant Person', superpower: 'Controls plants', age: 40},
      // { id: 35, name: 'Electric Person', superpower: 'Controls electricity', age: 40},
      // { id: 36, name: 'Shade Person', superpower: 'Controls shades and shadows', age: 40},
      // { id: 37, name: 'Light Person', superpower: 'Controls lights', age: 40},
      // { id: 38, name: 'Lucky McGee', superpower: 'Supernatural luck', age: 29},
      // { id: 39, name: 'D Grind', superpower: 'Stays with the grind', age: 29},
      // { id: 40, name: 'Money Machine', superpower: 'Creates wealth', age: 99},
      // { id: 41, name: 'Copyright Infringement', superpower: 'Creates copyright infringements', age: 50},
      // { id: 42, name: 'Legal Distinction', superpower: 'Able to make anything legally distinct', age: 23},
      // { id: 43, name: 'McDojo Ultrabelt', superpower: 'The peak of McDojo fake martial arts', age: 23},
      // { id: 44, name: 'Preacher', superpower: 'Like Reacher, but for Preaching', age: 61},
      // { id: 45, name: 'Teacher', superpower: 'Like Reacher, but for Teaching', age: 54},
      // { id: 46, name: 'Sleeper', superpower: 'Like Reacher, but for Sleeping', age: 44},
      // { id: 47, name: 'Bencher', superpower: 'Like Reacher, but for warming the bench', age: 22},
      // { id: 48, name: 'Bee Keeper', superpower: 'Like Reacher, but for keeping bees', age: 30},
      // { id: 49, name: 'Ditcher', superpower: 'Like Reacher, but for ditching obligations', age: 36},
      // { id: 50, name: 'Pitcher', superpower: 'Like Reacher, but for pitching objects', age: 41},
      // { id: 51, name: 'Creature', superpower: 'Can turn into any creature', age: 59},
      // { id: 52, name: 'Fixture', superpower: 'Fixed in places', age: 44},
      // { id: 53, name: 'Speaker', superpower: 'Like Reacher, but for speeches', age: 32},
      // { id: 54, name: 'Deeper', superpower: 'Like Reacher, but for reaching the deepest parts', age: 111},
      // { id: 55, name: 'Mixture', superpower: 'Like Reacher, but for mixing things', age: 65},
      // { id: 56, name: 'Besieger', superpower: 'Like Reacher, but for sieging fortification', age: 46},
      // { id: 57, name: 'Fever', superpower: 'Like Reacher, but for causing fevers', age: 30},
      // { id: 58, name: 'Beaver', superpower: 'Like Reacher, but for doing beaver things', age: 27},
      // { id: 59, name: 'Teamer', superpower: 'Like Reacher, but for teaming up with others', age: 17},
      // { id: 60, name: 'Fixer', superpower: 'Like Reacher, but fixes things', age: 29},
      // { id: 61, name: 'Mixer', superpower: 'Like Reacher, but mixes things', age: 33},
      // { id: 62, name: 'Max the Trickster', superpower: 'Like Reacher, but for tricking people', age: 15},
      // { id: 63, name: 'Sixerr', superpower: 'Like Reacher, but for doing odd jobs', age: 25},
      // { id: 64, name: 'Gamer', superpower: 'Like Reacher, but for gaming', age: 14},
      // { id: 65, name: 'Trainer', superpower: 'Like Reacher, but for training others', age: 44},
      // { id: 66, name: 'Sixty Sixer', superpower: 'Like Reacher, but for executing orders like Order 66', age: 66},
      // { id: 67, name: 'Drinker', superpower: 'Like Reacher, but capable for drinking anyone under the table', age: 32},
      // { id: 68, name: 'Smuggler', superpower: 'Like Reacher, but for smuggling anything and everything', age: 49},
      // { id: 69, name: 'Flexer', superpower: 'Like Reacher, but for flexing on everyone', age: 17},
      // { id: 70, name: 'Diss Disher', superpower: 'Like Reacher, but for dishing out disses', age: 18},
      // { id: 71, name: 'Washer', superpower: 'Like Reacher, but washing anything and everything', age: 31},
      // { id: 72, name: 'Forker', superpower: 'Like Reacher, but for forking pieces in chess', age: 49},
      // { id: 73, name: 'Farmer', superpower: 'Like Reacher, but for farming', age: 56},
      // { id: 74, name: 'Rancher', superpower: 'Like Reacher, but for doing things around the ranch', age: 61},
      // { id: 75, name: 'Trencher', superpower: 'Like Reacher, but for digging trenches', age: 120},
      // { id: 76, name: 'Drencher', superpower: 'Like Reacher, but for drenching otheres', age: 14},
      // { id: 77, name: 'Stencher', superpower: 'Like Reacher, but for working with stenches', age: 29},
      // { id: 78, name: 'Worker Freer', superpower: 'Like Reacher, but for freeing workers from the chains of their toil', age: 38},
      // { id: 79, name: 'Peter', superpower: 'Like Reacher, but not a Parker', age: 24},
      // { id: 80, name: 'Parker', superpower: 'Like Reacher, but not a Peter (and definitely not Spoderman)', age: 24},
      // { id: 81, name: 'Ranker', superpower: 'Like Reacher, but ranking up on the hero leaderboard', age: 31},
      // { id: 82, name: 'Tanker', superpower: 'For your dealing with fuel logistics', age: 42},
      // { id: 83, name: 'Slanderer', superpower: 'For slandering supervillains', age: 24},
      // { id: 84, name: 'Panderer', superpower: 'For pandering to everyone', age: 50},
      // { id: 85, name: 'Flounderer', superpower: 'For floudering any task', age: 8},
      // { id: 86, name: 'Stinker', superpower: 'For stinking up the place', age: 3},
      // { id: 87, name: 'Tester', superpower: 'For testing things', age: 30},
      // { id: 88, name: 'Jester', superpower: 'For jesting', age: 48},
      // { id: 89, name: 'Power Shufler', superpower: 'For shufling super powers around', age: 28},
      // { id: 90, name: 'Masher', superpower: 'For mashing villians up', age: 29},
      // { id: 91, name: 'Trasher', superpower: 'For trashing villian hideouts ', age: 34},
      // { id: 92, name: 'Dasher', superpower: 'For dashing around with your deliveries ', age: 28},
      // { id: 93, name: 'Cutlery Slasher', superpower: 'For slashing, but only cutlery', age: 41},
      // { id: 94, name: 'Animal Charmer', superpower: 'For charming animals to do your bidding', age: 55},
      // { id: 95, name: 'Pro-grammer', superpower: 'For helping with any programming needs', age: 48},
      // { id: 96, name: 'Trespasser', superpower: 'For trespassing into the secret bases of villains', age: 29},
      // { id: 97, name: 'Dismisser', superpower: 'For dismissing any and all claims', age: 72},
      // { id: 98, name: 'Coder', superpower: 'Like programmer, but for coding', age: 51},
      // { id: 99, name: 'Tro the Transponder', superpower: 'For passing on information', age: 49},
      // { id: 100, name: 'The Hundredth Centi-meter', superpower: 'For becoming the hundredth superhero', age: 100},
      // { id: 101, name: 'Dalmatian Pupeteer', superpower: 'Can control dalmatians - up to 101 of them at once', age: 101},
      // { id: 102, name: 'Randomer', superpower: 'Gains and loses a random superpower every hour', age: 38},
      // { id: 103, name: 'Forester', superpower: 'Like Reacher, but for taking care of forests', age: 26},
      // { id: 104, name: 'Misser', superpower: 'Like Reacher, but misses all the shots that he doesn't take', age: 45},
      // { id: 105, name: 'Redacted-er', superpower: 'Like Reacher, but superpower is redacted for redacted reasons', age: 000},
      // { id: 106, name: 'Breakfaster', superpower: 'Like Reacher, but controls all aspects of a breakfast', age: 31},
      // { id: 107, name: 'Luncher', superpower: 'Like Reacher, but sends you lunch wherever you are', age: 64},
      // { id: 108, name: 'Diner', superpower: 'Like Reacher, but creates diners in locations he spends more than 24 hours', age: 53},
      // { id: 109, name: 'Dinner', superpower: 'Like Reacher, but creates the best dinners regardless of what ingridients you have on hand', age: 49},
      // { id: 110, name: 'Traveler', superpower: 'Like Reacher, but travels around the world', age: 32},
      // { id: 111, name: 'Reveler', superpower: 'Like Reacher, but reveling in the joys of the world', age: 29},
      // { id: 112, name: 'Transferer', superpower: 'Transfers anything between himself and any other individual', age: 36},
      // { id: 113, name: 'Average Enjoyer', superpower: 'Makes everyone inside a 10m radius enjoy average things', age: 59},
      // { id: 114, name: 'Anime Personified', superpower: 'All the anime tropes personified', age: 1001},
      // { id: 115, name: 'Comic Tans', superpower: 'Funniest font comic', age: 48},
      // { id: 116, name: 'Cat Tamer', superpower: 'Tames the felines', age: 23},
      // { id: 117, name: 'Canine Whisperer', superpower: 'Legally disctinct, but still trains dogs', age: 51},
      // { id: 118, name: 'Feline Talker', superpower: 'Legally disctinct, but still trains cats', age: 69},
      // { id: 119, name: 'Joey Walker', superpower: 'Legally disctinct, but supposedly makes great whiskey', age: 27},
      // { id: 120, name: 'Torris Walker', superpower: 'Legally disctinct, Texas ranger', age: 38},
      // { id: 121, name: 'Iron Trainer', superpower: 'Trains other using iron tools', age: 38},
      // { id: 122, name: 'Duplicator', superpower: 'Can duplicate anything', age: 25},
      // { id: 123, name: 'Triplicator', superpower: 'Can triplicate anything', age: 43},
      // { id: 124, name: 'Quad-wheel-person', superpower: 'Can transform into a quad and drive around', age: 19},
      // { id: 125, name: 'Quixote Quintuplets', superpower: 'Quintuplets that can morf into Don Quixote', age: 48},
      // { id: 126, name: 'Dollar Hussler', superpower: 'Can make money on any odd job', age: 32},
      // { id: 127, name: 'Yen Enjoyer', superpower: 'Influences the Japanese economy', age: 68},
      // { id: 128, name: 'Eurocrat', superpower: 'Bureaucrat par excellence', age: 41},
      // { id: 129, name: 'Twenty-Niner', superpower: 'Permamently twenty-nine years old', age: 29},
      // { id: 130, name: 'Tiv the Motivator', superpower: 'Motivates others', age: 32},
      // { id: 131, name: 'Gravitator', superpower: 'Controls gravity around themselves', age: 40},
      // { id: 132, name: 'Tower Defender', superpower: 'Turns reality into a tower defense game', age: 24},
      // { id: 133, name: 'Castle Builder', superpower: 'Turns fortifications into Gothic castles', age: 67},
      // { id: 134, name: 'Speedy Reader', superpower: 'Fastest reader on planet Earth, but can only read e-books', age: 87},
      // { id: 135, name: 'Cal I. Grapher', superpower: 'Has the otherworldy handwriting', age: 121},
      // { id: 136, name: 'MeTouber', superpower: 'Best YT content creator', age: 20},
      // { id: 137, name: 'Shuder Streamer', superpower: 'Best streamer', age: 19},
      // { id: 138, name: 'Stock Stocker', superpower: 'Can stock anything for any shop', age: 37},
      // { id: 139, name: 'Stacker Hacker', superpower: 'Best hacker in the world', age: 35},
      // { id: 140, name: 'Juggler', superpower: 'Can juggle anything', age: 46},
      // { id: 141, name: 'Skill Passer', superpower: 'Can teach anyone any skill', age: 63},
      // { id: 142, name: 'Sport Maxer', superpower: 'Can play any sport at a professional level', age: 42},
      // { id: 143, name: 'Space Expander', superpower: 'Can create more space out of less', age: 58},
      // { id: 144, name: 'Moe the Mover', superpower: 'Can move anything from point A to point B', age: 67},
      // { id: 145, name: 'Harold the Healer', superpower: 'Can heal anyone', age: 36},
      // { id: 146, name: 'Bone Mender', superpower: 'Can heal any broken bone', age: 28},
      // { id: 147, name: 'Tendon Flexdon', superpower: 'Flexes any tendon to make it stronger', age: 41},
      // { id: 148, name: 'Meal Prepper', superpower: 'Can prep any meal out of nothing', age: 44},
      // { id: 149, name: 'Grandmaster', superpower: 'Can become a grandmaster in any sport', age: 73},
      // { id: 150, name: 'Track Meiser', superpower: 'Can track anything', age: 59},
      // { id: 151, name: 'Truck Driver', superpower: 'Like taxi driver, but cooler and a trucker', age: 38},
      // { id: 152, name: 'Duck Striver', superpower: 'Strives to be the best human-duck', age: 7},
      // { id: 153, name: 'Potato Masher', superpower: 'Like masher, but for potatoes only', age: 27},
      // { id: 154, name: 'Scent Refresher', superpower: 'Refreshes any scent', age: 62},
      // { id: 155, name: 'Set Typer', superpower: 'Can type anything', age: 46},
      // { id: 156, name: 'Tired Fired', superpower: 'Can make anyone tired', age: 32},
      // { id: 157, name: 'Flame Heater', superpower: 'Burns everything around them', age: 44},
      // { id: 158, name: 'Try Hard Mover', superpower: 'Can move anything if they try hard enough', age: 33},
      // { id: 159, name: 'Hype Train Conducter', superpower: 'Can conduct the largest hype trains', age: 26},
      // { id: 160, name: 'Choo Chew Chee', superpower: 'The living train', age: 51},
      // { id: 161, name: 'Review Rewind', superpower: 'Can rewind the last 5 seconds', age: 97},
      // { id: 162, name: 'Replay Rewinder', superpower: 'Can replay any game they participated in', age: 35},
      // { id: 163, name: 'Diplomancer', superpower: 'Can "diplo" anyone', age: 59},
      // { id: 164, name: 'Living Calculatron', superpower: 'Can calculate anything', age: 48},
      // { id: 165, name: 'Pod the Caster', superpower: 'Can turn anything into a podcast', age: 29},
      // { id: 166, name: 'T. D. Wut', superpower: 'Can confuse anyone', age: 37},
      // { id: 167, name: 'Waaaaa Zuuuuup', superpower: 'Side tracks anyone', age: 15},
      // { id: 168, name: 'Blanker', superpower: 'Can blank anyones memories', age: 00},
      // { id: 169, name: 'Traper', superpower: 'Can trap anyone', age: 77},
      // { id: 170, name: 'Nautilus the Fisher', superpower: 'Can catch anything that swims', age: 81},
      // { id: 171, name: 'Flexy Dexy', superpower: 'The most flexible human', age: 20},
      // { id: 172, name: 'Clear Eyes', superpower: 'Nothing clouds their vision', age: 48},
      // { id: 173, name: 'Pointy Ears', superpower: 'Allegedly not an elf, but has great hearing', age: 719},
      // { id: 174, name: 'Birb Individual', superpower: 'Half bird, half human, all flight', age: 13},
      // { id: 175, name: 'Bulb The Light', superpower: 'Always the brightest person in the room', age: 68},
      // { id: 176, name: 'Beer Chugger', superpower: 'Can drink an endless amount of beer', age: 55},
      // { id: 177, name: 'Beet Ruth', superpower: 'Sweetest person in the world', age: 48},
      // { id: 178, name: 'Berry Larry', superpower: 'Controls everything related to berries', age: 61},
      // { id: 179, name: 'Pine Lime', superpower: 'Neither a lime, nor a pine, still stubline', age: 74},
      // { id: 180, name: 'Seller Weller', superpower: 'Can sell anything', age: 36},
      // { id: 181, name: 'Cold Feet', superpower: 'Feet can freeze anything they touch', age: 34},
      // { id: 182, name: 'Hot Steps', superpower: 'Starts fires wherever they go', age: 47},
      // { id: 183, name: 'Fiery Look', superpower: 'Like Hot Steps but with whatever they look at', age: 51},
      // { id: 184, name: 'Add Ict', superpower: 'Can make anyone addicted to something', age: 87},
      // { id: 185, name: 'Ickinator', superpower: 'Can create an ick in anyone', age: 11},
      // { id: 186, name: 'Inso inducer', superpower: 'Induces insomania in others', age: 32},
      // { id: 187, name: 'Cre A. Tive inducer', superpower: 'Limitless creativity', age: 14},
      // { id: 188, name: 'Clear Glass', superpower: 'Can make anything transparent temporarily', age: 27},
      // { id: 189, name: 'Fore A. Ger', superpower: 'Can forage anything given enough time', age: 43},
      // { id: 190, name: 'Meth Teacher', superpower: 'Can teach anything about drugs', age: 51},
      // { id: 191, name: 'Alert Eyes', superpower: 'Tracks all alerts', age: 32},
      // { id: 192, name: 'Clean Coder', superpower: 'Cleans up any code', age: 50},
      // { id: 193, name: 'Alerter', superpower: 'Catches any alert before it alerts', age: 69},
      // { id: 194, name: 'Empt-ey', superpower: 'Creates emptiness', age: 58},
      // { id: 195, name: 'Full Lull', superpower: 'Creates fullness', age: 58},
      // { id: 196, name: 'Tale Spinner', superpower: 'Can create a fantastical tale out of any mundane story fullness', age: 83},
      // { id: 197, name: 'Gainer', superpower: 'Can help anyone achieve "gainz"', age: 46},
      // { id: 198, name: 'Strainer', superpower: 'Can strain anyone', age: 30},
      // { id: 199, name: 'R.O.T. Spinner', superpower: 'Turns everything into its opposite', age: 55},
      // { id: 200, name: 'Logger', superpower: 'Logs everything', age: 39},
      // { id: 201, name: 'TrackeRrr', superpower: 'Undefeatable as long as they are near a track', age: 61},
      // { id: 202, name: 'Swan Swimmer', superpower: 'Swims as gracefully as a swan', age: 46},
      // { id: 203, name: 'Tray Baker', superpower: 'Can bake anything', age: 27},
      // { id: 204, name: 'Death Strander', superpower: 'Strands death', age: 99},
      // { id: 205, name: 'Life Reader', superpower: 'Can tell the future', age: 86},
      // { id: 206, name: 'Rider', superpower: 'Can ride any animal', age: 45},
      // { id: 207, name: 'Vic Tor', superpower: 'Always wins', age: 31},
      // { id: 208, name: 'Buran', superpower: 'Controls extreme cold weather', age: 70},
      // { id: 209, name: 'Bright Scorch', superpower: 'Controls extreme hot weather', age: 70},
      // { id: 210, name: 'Whisk the Key', superpower: 'Creates the best hard liquor', age: 54},
      // { id: 211, name: 'Be E. R.', superpower: 'Can turn any liquid into the best beer', age: 38},
      // { id: 212, name: 'See Take', superpower: 'Can turn any meat into the great steak', age: 31},
      // { id: 213, name: 'Beenz Galore', superpower: 'Makes it so everyone ate a lot of beans', age: 19},
      // { id: 214, name: 'Scale Tale', superpower: 'Can temporarily turn peoples skin into dragon scale', age: 101},
      // { id: 215, name: 'Tea Tith', superpower: 'Can turn any liquid into tea', age: 54},
      // { id: 216, name: 'Lee Mon Ade', superpower: 'Can turn any liquid into lemonade', age: 51},
      // { id: 217, name: 'Vino Snob', superpower: 'Defeats everyone with their wine snobery', age: 43},
      // { id: 218, name: 'Chocolate Snail', superpower: 'A living contradiction', age: 2},
      // { id: 219, name: 'Amp Lamp', superpower: 'A source of light in dark times', age: 24},
      // { id: 220, name: 'Mughead', superpower: 'Legally distinct beverage holder head', age: 13},
      // { id: 221, name: 'Decanterhead', superpower: 'Older sibling of Mughead', age: 15},
      // { id: 222, name: 'Jarrrhead', superpower: 'Quintessential soldier', age: 19},
      // { id: 223, name: 'HeadHead', superpower: 'Twice the head, twice the wisdom', age: 88},
      // { id: 224, name: 'Feet Foot Fleet', superpower: 'More feet than anyone else', age: 32},
      // { id: 225, name: 'Fingers 4 Hands', superpower: 'Has fingers for hands', age: 41},
      // { id: 226, name: 'Knees & Toes', superpower: 'Ultimate in flexibility', age: 29},
      // { id: 227, name: 'Ham Sam', superpower: 'Turns any meat into ham', age: 73},
      // { id: 228, name: 'Swol Towel', superpower: 'Strongest towel out there', age: 33},
      // { id: 229, name: 'Teeth Paste', superpower: 'Cleans all your teeth and not just your tooth', age: 41},
      // { id: 230, name: 'Diamond Nailz', superpower: 'Nicest and toughest nails out there', age: 24},
      // { id: 231, name: 'Quintcep', superpower: 'Got muscles on top of muscles', age: 18},
      // { id: 232, name: 'T-Raptor', superpower: 'T-Rex sized raptor like hero', age: 63},
      // { id: 233, name: 'Duck Sock', superpower: 'Duck with socks', age: 4},
      // { id: 234, name: 'Fish Dish Mish', superpower: 'Off-brand aqua-person', age: 32},
      // { id: 235, name: 'LOLZ Cow', superpower: 'Can make anyone laugh', age: 21},
      // { id: 236, name: 'Comment Farmer', superpower: 'Can farm any comment', age: 16},
      // { id: 237, name: 'De Carto Graph', superpower: 'Can create a map for anything', age: 57},
      // { id: 238, name: 'Vaca Sine', superpower: 'Cow that creates antidotes', age: 5},
      // { id: 239, name: 'Cat Claw', superpower: 'Sharpest claws out there', age: 4},
      // { id: 240, name: 'Paper Sword', superpower: 'Mightiest sword wielder', age: 20},
      // { id: 241, name: 'Glass Armor', superpower: 'Strongest plot armor out there', age: 63},
      // { id: 242, name: 'Whole Puncher', superpower: 'Can punch something until its whole again', age: 58},
      // { id: 243, name: 'Hole Drawer', superpower: 'Can draw holes into anyone', age: 58},
      // { id: 244, name: 'Pencil Pusher', superpower: 'Like a paper pusher, but the opposite of bureaucractic', age: 44},
      // { id: 245, name: 'Sharper Marker', superpower: 'Can mark anything', age: 52},
      // { id: 246, name: 'Karl Curler', superpower: 'Can curl anything', age: 39},
      // { id: 247, name: 'Censored Censored', superpower: 'Can censore anything', age: 89},
      // { id: 248, name: 'Bard Beard', superpower: 'The beard IS the bard', age: 66},
      // { id: 249, name: 'Fidi Media', superpower: 'Can control the media', age: 37},
      // { id: 250, name: 'Puns of Damage', superpower: 'Deals more damage than you can imagine', age: 68},
      // { id: 251, name: 'Enemy of None', superpower: 'Has no enemies', age: 55},
      // { id: 252, name: 'Doe Foe', superpower: 'Can turn anyone into a foe', age: 32},
      // { id: 253, name: 'X. O.', superpower: 'Best second in command', age: 87},
      // { id: 254, name: 'K. O.', superpower: 'Instantly knocks out one entity per 24 hours', age: 53},
      // { id: 255, name: 'U. O. M.', superpower: 'Can make anyone owe them some money', age: 24},
      // { id: 256, name: 'etc', superpower: 'Goes on and on, forever', age: 75},
      // { id: 257, name: 'Ethic of Work', superpower: 'Instills a great work ethic in anyone', age: 49},
      // { id: 258, name: 'Hic of Booze', superpower: 'Can never get drunk but always has a hangover', age: 52},
      // { id: 259, name: 'Char I. Ot', superpower: 'Can drive anything that doesn't have an engine', age: 97},
      // { id: 260, name: 'Well Played', superpower: 'Turns any game into a well played game', age: 22},
      // { id: 261, name: 'Fan Stan', superpower: 'The fan of everyone and no one', age: 44},
      // { id: 262, name: 'Float Soar', superpower: 'Can make anything float', age: 67},
      // { id: 263, name: 'Grabby Grab', superpower: 'Can grab anything', age: 43},
      // { id: 264, name: 'Seeker Finder', superpower: 'Can find anything that was lost', age: 76},
      // { id: 265, name: 'Knot Forgotten', superpower: 'Can uncover anything that was forgotten', age: 76},
      // { id: 266, name: 'Zzz Sleepy', superpower: 'Can make anyone sleepy', age: 25},
      // { id: 267, name: 'Smart D-Bell', superpower: 'The smartest strongman', age: 37},
      // { id: 268, name: 'Impossible Dice', superpower: 'Gets impossible dice results', age: 7},
      // { id: 269, name: '200+Nice', superpower: 'The power of Nice!', age: 69},
      // { id: 270, name: 'Remember Knot', superpower: 'No one remembers them', age: 38},
      // { id: 271, name: 'K. Not', superpower: 'Can bind anyone', age: 71},
      // { id: 272, name: 'Ham E.R.', superpower: 'Punches that hit like pneumatic hammer strikes', age: 23},
      // { id: 273, name: 'Ctrl Ed Chaos.', superpower: 'Temporarily controls chaos', age: 56},
      // { id: 274, name: 'PigBearMan.', superpower: 'Like manbearpig, but a quarter pig, a quarter bear and a quarter man', age: 44},
      // { id: 275, name: 'Secure I. Ty', superpower: 'Can protect anyone', age: 37},
      // { id: 276, name: 'McBoat Face', superpower: 'Can control any floating object', age: 51},
      // { id: 277, name: 'Ferb Orb', superpower: 'Controls all orbs', age: 93},
      // { id: 278, name: 'Empty', superpower: 'Power of emptiness', age: 23},
      // { id: 279, name: 'Exercise Exorcist', superpower: 'Exorcism through the power of exercise', age: 58},
      // { id: 280, name: 'If Rit', superpower: 'Controls a demonic fire', age: 70},
      // { id: 281, name: 'Craw Caw', superpower: 'Communes with crows', age: 42},
      // { id: 282, name: 'Renter', superpower: 'Can rent anything within a budget', age: 30},
      // { id: 283, name: 'Derma Logist', superpower: 'Dermatalogist with a demonology minor', age: 28},
      // { id: 284, name: 'Little Colonel', superpower: 'Best artillery general', age: 43},
      // { id: 285, name: 'M. P.', superpower: 'Only hero able to police music taste', age: 37},
      // { id: 286, name: 'Genius Gold', superpower: 'Can turn anything into useable alloys', age: 75},
      // { id: 287, name: 'Dolphin Person', superpower: 'Like bird person, but dolphin', age: 25},
      // { id: 288, name: 'Six Gum', superpower: 'Stretchy, edgy but flaky', age: 13},
      // { id: 289, name: 'Yellow Snow', superpower: 'Most misunderstood hero', age: 43},
      // { id: 290, name: 'Brown Stein', superpower: 'Second most misunderstood hero', age: 53},
      // { id: 291, name: 'Soaker', superpower: 'Protector of hot springs', age: 51},
      // { id: 292, name: 'Boom Hair', superpower: 'Explosive hair folicles', age: 19},
      // { id: 293, name: 'Pain Gain', superpower: 'Gets stronger through pain', age: 24},
      // { id: 294, name: 'Chain Slab', superpower: 'Fights with chain slabs', age: 38},
      // { id: 295, name: 'Con Psi', superpower: 'Psionically concious', age: 57},
      // { id: 296, name: 'Traitor', superpower: 'Can betray anyone', age: 26},
      // { id: 297, name: 'Fire Pants', superpower: 'Can lie without burning pants', age: 39},
      // { id: 298, name: 'Doodle Poodle', superpower: 'Dog that can doodle', age: 4},
      // { id: 299, name: 'End Less', superpower: 'Has no end', age: 40},
      // { id: 300, name: 'Leo the Spartan', superpower: 'Real Spartan', age: 42},
      // { id: 301, name: 'End Naught', superpower: 'Endless', age: 38},
      // { id: 302, name: 'Bangs', superpower: 'Got the best bangs', age: 27},
      // { id: 303, name: '20th Belt', superpower: 'Master of the McDojo master', age: 89},
      // { id: 304, name: '304', superpower: 'If you know you know', age: 22},
      // { id: 305, name: 'Anti Bul-Ley', superpower: 'Grows more powerful when fighting bullies', age: 14},
      // { id: 306, name: 'Craven Lord', superpower: 'Turns his enemies into cowards', age: 19},
      // { id: 307, name: 'Nailz', superpower: 'Tough as plastic nails', age: 16},
      // { id: 308, name: 'Cat o' 10 tailz', superpower: 'Dishes out punishment to everyone', age: 29},
      // { id: 309, name: 'Waga Waga', superpower: 'The one true orkz', age: 43},
      // { id: 310, name: 'Paper Anchor', superpower: 'Immovable object...' age: 32},
      // { id: 311, name: 'MagiPunk', superpower: 'Punk with magic', age: 56},
      // { id: 312, name: 'Blanket-y', superpower: 'Magical power of a blanket', age: 3},
      // { id: 313, name: 'Acad Medic', superpower: 'Medic of All Academies', age: 38},
      // { id: 314, name: 'Feline Guardian', superpower: 'Indomitable guardian of ancient treasures', age: 38},
      // { id: 315, name: 'Treat Deet', superpower: 'Treats everyone to a good meal', age: 73},
      // { id: 316, name: 'Red One', superpower: 'Brings Xmas cheer to everyone', age: 48},
      // { id: 317, name: 'Green Fingers', superpower: 'Can grow anything', age: 57},
      // { id: 318, name: 'Chaosling', superpower: 'Spreads chaos to enemies', age: 36},
      // { id: 319, name: 'Dev VVeb', superpower: 'Makes the best web pages', age: 31},
      // { id: 320, name: 'Kitsch Lich', superpower: 'Brings back kitsch undead', age: 999},
      // { id: 321, name: 'Last First', superpower: 'First at being last', age: 13},
      // { id: 322, name: 'Coughinator', superpower: 'Can make anyone cough', age: 61},
      // { id: 323, name: 'Lost & Found', superpower: 'Finds what has been lost', age: 24},
      // { id: 324, name: 'Found Neva Mor', superpower: 'Makes things disappear forever', age: 23},
      // { id: 325, name: 'Tat Oooh', superpower: 'Can tatoo anyone or anything', age: 28},
      // { id: 326, name: 'Cow Scowl', superpower: 'Angriest bovine hero', age: 4},
      // { id: 327, name: 'Bow Miester', superpower: 'Performs the best bows', age: 49},
      // { id: 328, name: 'Furry Purr', superpower: 'Purr of Loyalty', age: 1},
      // { id: 329, name: 'Bo Wine', superpower: 'Can turn into a bovine', age: 19},
      // { id: 330, name: 'Nag Maximus', superpower: 'Can nag like no one else', age: 37},
      // { id: 331, name: 'Max Praise', superpower: 'Can praise like no one else', age: 37},
      // { id: 332, name: 'Box Tox', superpower: 'Can box anything', age: 24},
      // { id: 333, name: '3x3x3', superpower: 'The Box', age: 2},
      // { id: 334, name: 'Empty', superpower: 'Emptiness', age: 20},
      // { id: 335, name: 'Eye 4 Eye', superpower: 'Returns all damage equally', age: 31},
      // { id: 336, name: 'Kee Bored Fighter', superpower: 'Fights on the digital battleield', age: 24},
      // { id: 337, name: 'Salt Shaker', superpower: 'Salts any land', age: 53},
      // { id: 338, name: 'Pepper Member', superpower: 'Remembers everything', age: 76},
      // { id: 339, name: 'Sign Post', superpower: 'Creates the best signs', age: 38},
      // { id: 340, name: 'pSi G.', superpower: 'Psionic hero', age: 28},
      // { id: 341, name: 'Here they go', superpower: 'Returns people to a fixed event', age: 41},
      // { id: 342, name: 'Snackinator', superpower: 'Creates snacks out of thin air', age: 10},
      // { id: 343, name: 'Fruitinator', superpower: 'Like Snackinator but for fruit', age: 13},
      // { id: 344, name: 'Candee Nator', superpower: 'Like Snackinator but for candy', age: 7},
      // { id: 345, name: 'Push Sides', superpower: 'Can push anything', age: 27},
      // { id: 346, name: 'Pull Stripes', superpower: 'Can pull anything', age: 34},
      // { id: 347, name: 'Breath Power', superpower: 'Deadly breath', age: 45},
      // { id: 348, name: 'Looping Hero', superpower: 'Can send enemies on an endless loop', age: 66},
      // { id: 349, name: 'True Fighter', superpower: 'Hero of our time', age: 55},
      // { id: 350, name: 'Big Lamb', superpower: 'Nothing lil' about them', age: 7},
      // { id: 351, name: 'Iskr Der', superpower: 'Greatest conqueror', age: 33},
      // { id: 352, name: 'Sen Son Sun', superpower: 'Brightest hero', age: 40},
      // { id: 353, name: 'Mockrr', superpower: 'Can mock anything', age: 24},
      // { id: 354, name: 'Graderr', superpower: 'Can grade anything', age: 29},
      // { id: 355, name: 'Gametime', superpower: 'Turns everything into a game', age: 16},
      // { id: 356, name: 'Pianooooh', superpower: 'Piano damage to all', age: 38},
      // { id: 357, name: 'Up Top Law', superpower: 'Lawyer of the supers', age: 57},
      // { id: 358, name: 'Doc Rock', superpower: 'Heals with the power of rocks', age: 62},
      // { id: 359, name: 'Stock Dock', superpower: 'Logistics super', age: 38},
      // { id: 360, name: 'No Scope', superpower: 'No scope 360', age: 36},
      // { id: 361, name: 'Foot Spur', superpower: 'Wicked kick', age: 27},
      // { id: 362, name: 'Knuckle Toller', superpower: 'Hardest knuckles', age: 48},
      // { id: 363, name: 'Off Set', superpower: 'Offsets everything or anything', age: 81},
      // { id: 364, name: 'Note Ice', superpower: 'Notices everything', age: 28},
      // { id: 365, name: 'Year Tear', superpower: 'Controls yearly cycles', age: 49},
      // { id: 366, name: 'Long yEar', superpower: 'Controls leap years', age: 49},
      // { id: 367, name: 'Sticky Knees', superpower: 'Stickiest knees in the universe', age: 63},
      // { id: 368, name: 'Lock Dock', superpower: 'Strongest lock-er', age: 47},
      // { id: 369, name: '3x6x9', superpower: 'Power of Three', age: 33},
      // { id: 370, name: 'Brackets of Curls', superpower: 'Power of syntax', age: 58},
      // { id: 371, name: 'Pal Bearer', superpower: 'Best pall of all pallbearers', age: 43},
      // { id: 372, name: 'Data Pond', superpower: 'Younger sibling of Data Lake', age: 4},
      // { id: 373, name: 'Data Ocean', superpower: 'Older sibling of Data Lake', age: 6},
      // { id: 374, name: 'Data Planet', superpower: 'Oldest sibling of Data Lake', age: 14},
      // { id: 375, name: 'Brow Eye', superpower: 'Hypnotic eyebrows', age: 31},
      // { id: 376, name: 'Pot Dot', superpower: 'Pot warrior', age: 1},
      // { id: 377, name: 'Flying Desk', superpower: 'Heroic bureaucrat', age: 48},
      // { id: 378, name: 'Crawling Chair', superpower: 'Leads committees of heroes', age: 67},
      // { id: 379, name: 'Rug Dug', superpower: 'Can escape from any prison', age: 49},
      // { id: 380, name: 'Enginezzz', superpower: 'Heroic Engine', age: 33},
      // { id: 381, name: 'Debateer', superpower: 'Bucaneer of debating', age: 41},
      // { id: 382, name: 'Scalpel Fingers', superpower: 'Heroic surgeon', age: 53},
      // { id: 383, name: 'Bubble Pants', superpower: 'Floating pants', age: 14},
      // { id: 384, name: 'Navigator', superpower: 'Can navigate anywhere', age: 50},
      // { id: 385, name: 'Ali Gator', superpower: 'Gatorest gator drink creator', age: 22},
      // { id: 386, name: 'Croc Doc Nile', superpower: 'Crock the Doctor of Heroes', age: 24},
      // { id: 387, name: 'No Comment', superpower: 'No comment', age: 34},
      // { id: 388, name: 'Info Overlord', superpower: 'Overloads everyone on info', age: 68},
      // { id: 389, name: 'Info Trivia', superpower: 'Provides random heroic trivia, heroically', age: 31},
      // { id: 390, name: 'Fender Bender', superpower: 'Bends all the fenders with a thought', age: 45},
      // { id: 391, name: 'Trender', superpower: 'Creates trends out of thin air', age: 58},
      // { id: 392, name: 'Draw Claw', superpower: 'Draws claws onto everything', age: 3},
      // { id: 393, name: 'Hairy Wizard', superpower: 'Hairy is a wizard!', age: 15},
      // { id: 394, name: 'Can NON', superpower: 'Living canon', age: 31},
      // { id: 395, name: 'Art Dart Smart', superpower: 'Indirect fire hero', age: 40},
      // { id: 396, name: 'Border Gore', superpower: 'Destroys borders', age: 56},
      // { id: 397, name: 'Dore Bore', superpower: 'Heroic boredom', age: 20},
      // { id: 398, name: 'TVinator', superpower: 'Turns anything into a TV show', age: 67},
      // { id: 399, name: 'Conceptinator', superpower: 'Creates concepts out of thin air', age: 21},
      // { id: 400, name: 'Worst Request', superpower: 'From bad to worst requests', age: 11},
      // { id: 401, name: 'Re Cord', superpower: 'Records everything', age: 86},
      // { id: 402, name: 'Coma Comma', superpower: 'Puts anyone into a coma if they forgot a comma', age: 46},
      // { id: 403, name: 'Auth Forbidden', superpower: 'Forbids access', age: 28},
      // { id: 404, name: 'Found Knot', superpower: 'Can't be found only lost', age: 21},
      // { id: 405, name: 'Gobble Gobble', superpower: 'Turkey of Doom', age: 2},
      // { id: 406, name: 'Ship It', superpower: 'Ships anything', age: 35},
      // { id: 407, name: 'Whack It', superpower: 'Whacks anything', age: 32},
      // { id: 408, name: 'LED Fred', superpower: 'Brightest hero', age: 49},
      // { id: 409, name: 'Spark El Jewel', superpower: 'Turns anything into a jewel', age: 60},
      // { id: 410, name: 'Spike Ball', superpower: 'Spikiest hero', age: 43},
      // { id: 411, name: 'Spike Rock', superpower: 'Rockiest hero', age: 43},
      // { id: 412, name: 'Dee Jay', superpower: 'Heroic DJ', age: 24},
      // { id: 413, name: 'Monkee Stronk', superpower: 'Channels inner monkey strength', age: 9},
      // { id: 414, name: 'Monkee Smort', superpower: 'Channels inner monkey smarts', age: 10},
      // { id: 415, name: 'Monkee Trickee', superpower: 'Channels inner monkey trickery', age: 11},
      // { id: 416, name: 'Monkee Flex', superpower: 'Channels inner monkey flexibility', age: 12},
      // { id: 417, name: 'Monkee Stretchee', superpower: 'Channels inner monkey strechiness', age: 13},
      // { id: 418, name: 'Monkee Jumpee', superpower: 'Channels inner monkey jumpiness', age: 8},
      // { id: 419, name: 'Monkee Climbee', superpower: 'Channels inner monkey climbing skills', age: 28},
      // { id: 420, name: 'Monkee Blazee', superpower: 'Channels inner monkey free spirit', age: 14},
      // { id: 421, name: 'Big Man', superpower: 'Big Man Thing', age: 31},
      // { id: 422, name: 'Shout Out', superpower: 'Shout outs anything and everything', age: 26},
      // { id: 423, name: 'Block Crafter', superpower: 'Makes blocks out of everything', age: 15},
      // { id: 424, name: 'Fact Or Io', superpower: 'Makes factories for anything', age: 38},
      // { id: 425, name: 'Spit D Facts', superpower: 'Only speaks in facts', age: 31},
      // { id: 426, name: 'Worse Santa', superpower: 'The Santa that we deserve', age: 87},
      // { id: 427, name: 'Purple Prisoner', superpower: 'Can imprison anyone with the power of purple', age: 38},
      // { id: 428, name: 'Per Ser Vee', superpower: 'Heroic perseverance', age: 38},
      // { id: 429, name: 'Collector', superpower: 'Can collect anything', age: 49},
      // { id: 430, name: 'Collector Supreme', superpower: 'Can collect anything that is branded', age: 48},
      // { id: 431, name: 'PackageRRR', superpower: 'Can package anything', age: 37},
      // { id: 432, name: 'RansackeRRR', superpower: 'Can ransack anything', age: 23},
      // { id: 433, name: 'Ham Dam', superpower: 'Busts any dam', age: 26},
      // { id: 434, name: 'Spectre Tator', superpower: 'Spectates all events', age: 43},
      // { id: 435, name: 'Tin Paladin', superpower: 'Caricature of a true paladin', age: 38},
      // { id: 436, name: 'Loader', superpower: 'Can carry any load', age: 27},
      // { id: 437, name: 'MM', superpower: 'Power of milimeters', age: 33},
      // { id: 438, name: 'Negotiator', superpower: 'Can negotiate any deal', age: 43},
      // { id: 439, name: 'Kid Sitter', superpower: 'Can sit anyone', age: 16},
      // { id: 440, name: 'Catcher', superpower: 'Can catch anyone', age: 19},
      // { id: 441, name: 'Stack Stacker', superpower: 'Stacks stacks', age: 22},
      // { id: 442, name: 'Stacker Flower', superpower: 'Overflows stacks', age: 23},
      // { id: 443, name: 'Fly Flower', superpower: 'Creates flowers out of thin air', age: 24},
      // { id: 444, name: 'Fly Tower', superpower: 'Towers over all flies', age: 21},
      // { id: 445, name: 'Fly Swat TRRRRR', superpower: 'Swats fliers', age: 20},
      // { id: 446, name: 'Fly Biter', superpower: 'Bites whatever flies', age: 19},
      // { id: 447, name: 'Try Dry', superpower: 'Dries whatever they try', age: 34},
      // { id: 448, name: 'Dry Cry', superpower: 'Cries others dry', age: 41},
      // { id: 449, name: 'Duller Caller', superpower: 'Bores people through calls into inaction', age: 52},
      // { id: 450, name: 'Dullrrd', superpower: 'Dulls anyone', age: 38},
      // { id: 451, name: 'Maroon Arms', superpower: 'Perpetual arm pump that act like guns', age: 23},
      // { id: 452, name: 'Dines Mine', superpower: 'Dines to mine', age: 27},
      // { id: 453, name: 'Charge Ine', superpower: 'Charges everything', age: 31},
      // { id: 454, name: 'Plankinator', superpower: 'Unstoppable plank warrior', age: 11},
      // { id: 455, name: 'Paininator', superpower: 'Grows stronger through pain', age: 19},
      // { id: 456, name: 'Shin Shingle', superpower: 'Shins of shingle', age: 23},
      // { id: 457, name: 'Test Crusher', superpower: 'Crushes tests', age: 33},
      // { id: 458, name: 'Chillio', superpower: 'Makes others chill out', age: 26},
      // { id: 459, name: 'Point Up', superpower: 'Ups the points', age: 38},
      // { id: 460, name: 'Oint Fly', superpower: 'Gets in everyones way', age: 32},
      // { id: 461, name: 'Inv Es En Tor', superpower: 'Invests and invents heroically', age: 51},
      // { id: 462, name: 'Rookie Numbers', superpower: 'Makes others have only rookie numbers', age: 22},
      // { id: 463, name: 'Vistor', superpower: 'Can visit anywhere', age: 28},
      // { id: 464, name: 'Sol Rrr', superpower: 'Pirate of Sol', age: 34},
      // { id: 465, name: 'Spaghetti Coder', superpower: 'Writes the best spaghetti code', age: 31},
      // { id: 466, name: 'DeCode Pasta', superpower: 'Decodes spaghetti code', age: 33},
      // { id: 467, name: 'Paper Thrower', superpower: 'Can swamp any problem in paperwork', age: 47},
      // { id: 468, name: 'Scissor Sharpener', superpower: 'Sharpest scissor thumbs', age: 16},
      // { id: 469, name: 'Atmospheric Shield', superpower: 'Can shield others from air threats', age: 45},
      // { id: 470, name: 'pInter', superpower: 'Pint intern', age: 19},
      // { id: 471, name: 'dInter', superpower: 'Dinting intern', age: 17},
      // { id: 472, name: 'prInter', superpower: 'Printing intern', age: 20},
      // { id: 473, name: 'sprInter', superpower: 'Sprinting intern, for coffee ofc', age: 18},
      // { id: 474, name: 'tInter', superpower: 'Intern tinting windows, heroically', age: 17},
      // { id: 475, name: 'stInter', superpower: 'Intern for spending stints in prison', age: 19},
      // { id: 476, name: 'Faller', superpower: 'Can fall, just like Rome', age: 48},
      // { id: 477, name: 'Byzantine Planner', superpower: 'Creates the most byzantine plans', age: 31},
      // { id: 478, name: 'Last True Roman', superpower: 'Maximus Decimus', age: 42},
      // { id: 479, name: 'First Holy Roman', superpower: 'Neither Roman, nor holy, nor the first, but still a hero', age: 50},
      // { id: 480, name: 'Known Factor', superpower: 'The heroic factor', age: 26},
      // { id: 481, name: 'Tennis Baller', superpower: 'Baller tennis player', age: 23},
      // { id: 482, name: 'Den Faller', superpower: 'Collapses any den', age: 25},
      // { id: 483, name: 'Tren Troller', superpower: 'Heroic trolling through tren', age: 21},
      // { id: 484, name: 'hAnd Bagger', superpower: 'Heroic travel where everything fits in the hand bag', age: 29},
      // { id: 485, name: 'Floor Sleeper', superpower: 'Can sleep anywhere', age: 32},
      // { id: 486, name: 'Floor Sweeper', superpower: 'Sweeps the floor with any enemy', age: 37},
      // { id: 487, name: 'Bot Tod', superpower: 'The Tod of all Bots', age: 49},
      // { id: 488, name: 'Snot Rod', superpower: 'Most infectious hero', age: 57},
      // { id: 489, name: 'Toast Toaster', superpower: 'Heroic toasts', age: 42},
      // { id: 490, name: 'Toxic Peanut', superpower: 'Most toxic hero', age: 53},
      // { id: 491, name: 'Safe Walnut', superpower: 'Protects with all its being', age: 28},
      // { id: 492, name: 'Spicy Doe', superpower: 'Heroism powered by spice', age: 33},
      // { id: 493, name: 'Thunder Driver', superpower: 'Drives better the worse the weather', age: 29},
      // { id: 494, name: 'Giga Golf', superpower: 'Turns the world into a golf course', age: 46},
      // { id: 495, name: 'Cold Balooner', superpower: 'Can fly any sized baloon', age: 17},
      // { id: 496, name: 'Swift Biff', superpower: 'Swiftest sailor', age: 38},
      // { id: 497, name: 'Big n Tall', superpower: 'Largest hero', age: 60},
      // { id: 498, name: 'Tram Tychoon', superpower: 'Controls all trams', age: 71},
      // { id: 499, name: 'Gym Beaver', superpower: 'Like gym rat, but heroic', age: 34},
      // { id: 500, name: 'D 500', superpower: 'Halfway there to full heroic automation', age: 20},
      // { id: 501, name: 'Bee Sales', superpower: 'Can make anything go on sale', age: 44},
      // { id: 502, name: 'Coral Fire', superpower: 'Burns underwater', age: 31},
      // { id: 503, name: 'Paper Flier', superpower: 'Turns into a paper airplane to fly', age: 56},
      // { id: 504, name: 'Cardboard Floater', superpower: 'Turns into a cardboard ship to sail the seas', age: 49},
      // { id: 505, name: 'Five Oh Five', superpower: 'Sighs of five', age: 55},
      // { id: 506, name: 'Redeemer', superpower: 'Can redeem anything', age: 11},
      // { id: 507, name: 'Organizer', superpower: 'Can organize anything', age: 28},
      // { id: 508, name: 'Hop Dancer', superpower: 'Dances with a hop... and magic', age: 30},
      // { id: 509, name: 'Hop Brewer', superpower: 'Dances with beers, heroically', age: 21},
      // { id: 510, name: 'Boot Leg Dev', superpower: 'A developer with boots for legs', age: 24},
      // { id: 511, name: 'Boost Leg', superpower: 'Rockets for sprinting', age: 22},
      // { id: 512, name: 'True Thumb', superpower: 'Lie detector thumb', age: 34},
      // { id: 513, name: 'Wannabee', superpower: 'A bee that wants to be a hero', age: 1},
      // { id: 514, name: 'Wannatree', superpower: 'A tree that wants to walk', age: 371},
      // { id: 515, name: 'WannaCry', superpower: 'Hero of Ransoms', age: 45},
      // { id: 516, name: 'WannaDrool', superpower: 'Causes enemies to drool uncontrollably', age: 31},
      // { id: 517, name: 'WannaLaugh', superpower: 'Causes uncontrollable laughter in everyone', age: 22},
      // { id: 518, name: 'WannaHide', superpower: 'Cannot be found', age: 30},
      // { id: 519, name: 'WannaFly', superpower: 'Can only fly', age: 11},
      // { id: 520, name: 'WannaSing', superpower: 'Hypnotic singing', age: 19},
      // { id: 521, name: 'WannaSleep', superpower: 'Causes enemies to fall asleep... permanently', age: 33},
      // { id: 522, name: 'WannaQuit', superpower: 'Demoralizes everyone around them', age: 28},
      // { id: 523, name: 'WannaZap', superpower: 'Magnetic zaps', age: 20},
      // { id: 524, name: 'WannaTrap', superpower: 'Traps any villain', age: 42},
      // { id: 525, name: 'WannaDrop', superpower: 'Can drop anyone', age: 31},
      // { id: 526, name: 'WannaShine', superpower: 'Can shine anyone or anything', age: 53},
      // { id: 527, name: 'WannaBless', superpower: 'Provides boons to allies', age: 65},
      // { id: 528, name: 'WannaType', superpower: 'Types heroically', age: 49},
      // { id: 529, name: 'Emote Roll', superpower: 'Influences emotions', age: 21},
      // { id: 530, name: 'Marketeer', superpower: 'Creates best market prices', age: 24},
      // { id: 531, name: 'Phonee', superpower: 'Phoniest hero, with a phone', age: 23},
      // { id: 532, name: 'Medium Ez', superpower: 'Makes everything sort of easy', age: 30},
      // { id: 533, name: 'Large Bald', superpower: 'Makes villains bald', age: 51},
      // { id: 534, name: 'Small Mald', superpower: 'Makes everyone mald around them', age: 62},
      // { id: 535, name: 'Patent Troll', superpower: 'Scourge of companies', age: 39},
      // { id: 536, name: 'Brother Short Legs', superpower: 'Knock off spider superpowers', age: 24},
      // { id: 537, name: 'Sister Mister', superpower: 'Fixes and breaks any lock', age: 26},
      // { id: 538, name: 'Tired Tire', superpower: 'Rolls tiredness on everyone', age: 23},

    ];
    return {heroes};
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(heroes: Hero[]): number {
    return heroes.length > 0 ? Math.max(...heroes.map(hero => hero.id)) + 1 : 11;
  }
}
